export const SUBSCRIPTION_REVEALS_AMOUNT = 30
export const POINTS_PER_EVALUATION_REWARD = 4

export const MIN_DOCUMENTS_TO_EARN_POINTS = 4

export const REVEALS_EXPIRATION_MONTHS = 1
export const POINT_EXPIRATION_DAYS = 30
export const AUTO_REJECT_DELAY_HOURS = 24
export const DOCUMENT_DELETION_DELAY_AFTER_REJECTION_DAYS = 180


export const MIN_DOCUMENTS_FOR_STRIKE_CHECK = 25
export const MIN_APPROVAL_LEVEL_FOR_STRIKE_CHECK = 25

export const INITIAL_STRIKE_COUNTER = 12

export const STRIKE_LEVEL_1 = 8
export const STRIKE_LEVEL_2 = 4
export const STRIKE_LEVEL_MAX = 0

export const BLOCKING_DURATION_HOURS_LEVEL_1 = 48
export const BLOCKING_DURATION_HOURS_LEVEL_2 = 72
export const BLOCKING_DURATION_FOREVER = new Date('9999-12-31T23:59:59.999Z')

export const MAX_RECOMMENDATION_ITEMS = 6



export const AUTOCOMPLETE_HINT_LIMIT = 20
export const AUTOCOMPLETE_LIST_HINTS_LIMIT = 20



export const POINT_REWARD_EVALUATION_INTERVAL = 4
export const MIN_UNLOCKS_FOR_DISLIKE_CHECK = 3
export const MAX_UNLOCKS_FOR_DISLIKE_CHECK = 4
export const AUTO_REJECT_DISLIKE_THRESHOLD = 3



export const POINTS_TO_UNLOCK_DOCUMENT = 4
export const REVEALS_TO_UNLOCK_DOCUMENT = 1


export const USER_DAILY_COMPLAINT_LIMIT = 5